// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace AndanteTribe.IO.Unity
{
    internal static unsafe partial class LocalPrefsNative
    {
#if UNITY_WEBGL && !UNITY_EDITOR
        private const string DllName = "__Internal";
#else
        private const string DllName = "local_prefs_native";
#endif
        





        /// <summary>
        ///  Saves a UTF-8 value to browser local storage.
        ///
        ///  # Safety
        ///
        ///  `key` and `value` must point to valid null-terminated UTF-8 strings for the duration of the call.
        /// </summary>
        [DllImport(DllName, EntryPoint = "local_prefs_save_to_local_storage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void local_prefs_save_to_local_storage(byte* key, byte* value);

        /// <summary>
        ///  Deletes a value from browser local storage.
        ///
        ///  # Safety
        ///
        ///  `key` must point to a valid null-terminated UTF-8 string for the duration of the call.
        /// </summary>
        [DllImport(DllName, EntryPoint = "local_prefs_delete_from_local_storage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void local_prefs_delete_from_local_storage(byte* key);

        /// <summary>
        ///  Loads a UTF-8 value from browser local storage.
        ///
        ///  # Safety
        ///
        ///  `key` must point to a valid null-terminated UTF-8 string for the duration of the call. The
        ///  returned pointer must be released exactly once with [`local_prefs_free`].
        /// </summary>
        [DllImport(DllName, EntryPoint = "local_prefs_load_from_local_storage", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* local_prefs_load_from_local_storage(byte* key);

        /// <summary>
        ///  Releases memory allocated by the embedded browser bridge.
        ///
        ///  # Safety
        ///
        ///  `pointer` must be null or a pointer returned by `local_prefs_load_from_local_storage` that has
        ///  not already been released.
        /// </summary>
        [DllImport(DllName, EntryPoint = "local_prefs_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void local_prefs_free(void* pointer);

        /// <summary>
        ///  Starts an IndexedDB save operation.
        ///
        ///  # Safety
        ///
        ///  All pointers must remain valid until the embedded browser bridge has copied their values.
        ///  `success` and `error` must be valid C callback pointers with the signatures expected by the
        ///  bridge.
        /// </summary>
        [DllImport(DllName, EntryPoint = "local_prefs_save_to_indexed_db", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void local_prefs_save_to_indexed_db(void* state, byte* key, byte* data, int data_size, void* success, void* error);

        /// <summary>
        ///  Starts an IndexedDB delete operation.
        ///
        ///  # Safety
        ///
        ///  `key` must remain valid until the embedded browser bridge has copied it. `success` and `error`
        ///  must be valid C callback pointers with the signatures expected by the bridge.
        /// </summary>
        [DllImport(DllName, EntryPoint = "local_prefs_delete_from_indexed_db", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void local_prefs_delete_from_indexed_db(void* state, byte* key, void* success, void* error);

        /// <summary>
        ///  Starts an IndexedDB load operation.
        ///
        ///  # Safety
        ///
        ///  `key` must remain valid until the embedded browser bridge has copied it. `success` and `error`
        ///  must be valid C callback pointers with the signatures expected by the bridge.
        /// </summary>
        [DllImport(DllName, EntryPoint = "local_prefs_load_from_indexed_db", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void local_prefs_load_from_indexed_db(void* state, byte* key, void* success, void* error);


    }



}
