name: unity-test (github-hosted ubuntu-latest)
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
    - main
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/cache@v4
          with:
            path: |
              src/LocalPrefs.Unity/Library
              src/LocalPrefs.Unity/Packages/nuget-packages/InstalledPackages
              src/LocalPrefs.Unity/Packages/nuget-packages/InstalledPackages.meta
            key: cache-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
            restore-keys: |
              cache-
        - name: Free disk space
          run:  |
            chmod +x ./.github/workflows/scripts/free_disk_space.sh
            .github/workflows/scripts/free_disk_space.sh
            git checkout -- ./.github/workflows/scripts/free_disk_space.sh
        - uses: game-ci/unity-test-runner@v4
          id: tests
          env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          with:
            projectPath: src/LocalPrefs.Unity
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            unityVersion: auto
            testMode: editmode
            coverageOptions: 'generateHtmlReport;generateAdditionalReports;assemblyFilters:+LocalPrefs.Tests'
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Test results
            path: artifacts
            retention-days: 2
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Coverage Results
            path: CodeCoverage
            retention-days: 2
        - name: Upload Coverage Report
          run: |
            for file in CodeCoverage/**/Summary.md; do
              if [ -f "$file" ]; then
                cat "$file" >> $GITHUB_STEP_SUMMARY
              fi
            done
